### ISSUE TITLE
Setup testing on travis

### ISSUE THREAD

**Issue by Baschdl** [KDD-OpenSource/neo4j-graph-algorithms#1]
In the moment `.travis.yml` contains just some benchmarks. It should be really straightforward and easy to setup testing in Java on travis. If you have some problems, just ask.

**Comment by Baschdl** [comment]
We could also build the docker container each time and let Travis fail if our tests fail.

**Comment by GittiHab** [comment]
It already runs the tests on Travis – currently it's even failing.
